language: ruby
cache: bundler
services:
  - postgresql
  - redis-server
  - xvfb
sudo: false
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
  artifacts:
    paths:
      - $(ls -d -1 $PWD/tmp/capybara/* | tr "\n" ":")
env:
  - "DB=postgresql"
before_install:
  - nvm install 8
install:
  - bundle install
  - npm install
  - npm install --global yarn
  - yarn install
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp .env.sample .env"
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 2.6.0
script:
  - "bundle exec rake travis"
  - "bundle exec codeclimate-test-reporter"
  - "yarn test:ci"
